services:
  tests:
    container_name: tests-barrel-monitor
    build: .
    volumes:
      - ./playwright-report:/app/playwright-report
    working_dir: /app
    command: ["npx", "playwright", "test"]
